version: '3'
volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
services:
  mongo:
    container_name: mongo
    image: mongo:3.4
    command: --nojournal
  postgresql:
    container_name: postgresql
    build:
      context: ./
      dockerfile: postgresql/Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ckan
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  orion:
    container_name: orion
    image: fiware/orion
    links:
      - mongo
    ports:
      - 8091:1026
    command: -dbhost mongo
  comet:
    container_name: comet
    image: fiware/sth-comet
    links:
      - mongo
    ports:
      - 8092:8666
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=mongo
  solr:
    container_name: solr
    image: ckan/solr
  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - 8800:8800
  redis:
    container_name: redis
    image: redis:latest
  ckan:
    container_name: ckan
    image: ckan/ckan
    depends_on:
      - postgresql
      - solr
      - redis
    ports:
      - 0.0.0.0:${CKAN_PORT}:5000
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@postgresql:5432/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@postgresql:5432/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@postgresql:5432/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=http://${HOST_FQN}
      - CKAN_MAX_UPLOAD_SIZE_MB=100
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
